### ISSUE TITLE
Some tests crashing on macOS due to fork() 

### ISSUE THREAD

**Issue by lleifermann** [goloveychuk/fastest-jest-runner#9]
Hey there! I came across this amazing repo while investigating how to speed up our memory hogging test suite. I am completely flabbergasted by the ingenuity behind this runner. **Really well done**. 

Running my tests on a Linux machine is no problem. All tests run fine and it seems the processes correctly fork. 
Running the same tests on macOS 13.2.1 however makes **_some_** tests fail with the following error: 

```
objc[59483]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

I am not too familiar with macOS internal workings but judging by this blog post: http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html

It seems to be related on how macOS handles thread safety of forked child processes. Not sure why this is not a problem on any other Linux Distro though. 

Exporting `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` before running the tests fixed it for me but i am unsure if this would be the best approach. 

Is this behaviour something that should be fixed here with one of the suggestions in the link i shared above, or can this be safely ignored with the env var?

**Comment by goloveychuk** [comment]
If failed tests are consistent, seems like some of them are loading node extension written in objc... Right?
Otherwise Idk where you got objc runtime. I doubt nodejs has macos specific objc code. 
From docs you linked - seems like there is no safe way to fork processes with objc runtime. 
First you need to check where you got that runtime.
